### ISSUE TITLE
better readme for wasm package

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/message-parser#11]
add an example before the building commands stuff, so that https://www.npmjs.com/package/@deltachat/message_parser_wasm is nicer to look at.
maybe copy some stuff from the other root-readme file?

**Comment by farooqkz** [comment]
Is this still relevant? The current npm page is good I'd say at a first glance.

**Comment by Simon-Laux** [comment]
yeah I also guess it's fine for now, could still be improved but as there are no concrete points here, we can close this and open a new issue once we have concrete points
