### ISSUE TITLE
links that have non spec chars in the location part are not clickable

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/message-parser#16]
affected links are:
- https://delta.chat/üäö
- the Persian one on https://support.delta.chat/t/problem-with-shared-links-that-contain-other-languages/1645/5
- https://www.erbrechtsinfo.com/allgemeines-erbrecht/pflichtteilsergaenzungsanspruch-niessbrauch/#:~:text=Wird%20ein%20Nießbrauch%20bei%20einer,Schenkenden%20herausfallen%2C%20einen%20Pflichtteilsergänzungsanspruch%20auslösen. (`~`, `ß`, `ä`, `ö`)
- https://move-it-sportcamps.de/krafttraining-kinder-jugendliche/#:~:text=Sch%C3%A4dliche%20Nebenwirkungen%20beim%20Krafttraining%20f%C3%BCr,Leichtathletik%20als%20bessere%20Alternative%20gelten.
- https://int.bahn.de/en/buchung/fahrplan/suche#sts=true&so=Freiburg(Breisgau)%20Hbf&zo=Gl%C3%BCckstadt&kl=2&r=13:16:KLASSENLOS:1&soid=A%3D1%40O%3DFreiburg(Breisgau)%20Hbf%40X%3D7841174%40Y%3D47997696%40U%3D80%40L%3D8000107%40B%3D1%40p%3D1695240090%40&zoid=A%3D1%40O%3DGl%C3%BCckstadt%40X%3D9428318%40Y%3D53788610%40U%3D80%40L%3D8002293%40B%3D1%40p%3D1695240090%40&hd=2023-09-23T08:00:59&hza=D&ar=false&s=true&d=false&hz=%5B%5D&fm=false&bp=false

this only affects the location/file-path part, uff-8 chars are supported in the hostname:
- münchen.de

**Comment by dev24126** [comment]
See also [Text fragments | MDN](https://developer.mozilla.org/en-US/docs/Web/Text_fragments) about ":~:text=" within links.
