### ISSUE TITLE
Do not parse last dot for email addresses

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/message-parser#19]
```
you can reach me on me@provider.tld.
```
should be parsed to
```
[
 Text("you can reach me on ").
 Email("me@provider.tld"),
 Text("."),
]
```

**Comment by r10s** [comment]
same for `you can reach me on foo@bar.de!`, or `can you text me on  you can reach me on foo@bar.de?` - they are also wrong currently. probably also other characters.

**Comment by r10s** [comment]
nb: maybe it helps: urls ending with a dot are parsed as expected, sth. as
```
this is a https://test.com. bla.
```
