### ISSUE TITLE
implement methods/checks prevent/forbid panics

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/message-parser#25]
A. possibly enable more clippy checks (we already added some of them)
B. manually reviewing code?
C. try using https://docs.rs/no-panic/latest/no_panic/  (in different profile as a ci check), but @Hocuri isn't convinced that it will help, although we can still try

**Comment by Hocuri** [comment]
A. in the deltachat crate we have:
```rust
#![warn(
    unused,
    clippy::correctness,
    missing_debug_implementations,
    missing_docs,
    clippy::all,
    clippy::indexing_slicing,
    clippy::wildcard_imports,
    clippy::needless_borrow,
    clippy::cast_lossless,
    clippy::unused_async
)]
```
Could also add `#![cfg_attr(not(test), warn(clippy::unwrap_used, clippy::expect_used))]`

**Comment by Simon-Laux** [comment]
I think it's ok, if panics should appear we can reopen this issue.
