### ISSUE TITLE
Add HTML output

### ISSUE THREAD

**Issue by link2xt** [deltachat/message-parser#37]
For integration into platforms that support HTML like Android and Qt we need an HTML output rather than a custom output format.

Currently HTML rendering happens only in the JavaScript code: https://github.com/deltachat/message-parser/blob/ad0389f15586c2fd996b6d5c0ad242cdc135389d/message_parser_wasm/example.js

**Comment by Simon-Laux** [comment]
also needs sanitation to protect from XSS attacks, the way we do it in javascript creates DOM elements directly not HTML, in a way that is not vulnerable for XSS injections.
