### ISSUE TITLE
link from bahn.de not recognised

### ISSUE THREAD

**Issue by r10s** [deltachat/message-parser#45]
the following link does not work in desktop ...

https://int.bahn.de/en/buchung/fahrplan/suche#sts=true&so=Freiburg(Breisgau)%20Hbf&zo=Glückstadt&kl=2&r=13:16:KLASSENLOS:1&soid=A%3D1%40O%3DFreiburg(Breisgau)%20Hbf%40X%3D7841174%40Y%3D47997696%40U%3D80%40L%3D8000107%40B%3D1%40p%3D1695240090%40&zoid=A%3D1%40O%3DGlückstadt%40X%3D9428318%40Y%3D53788610%40U%3D80%40L%3D8002293%40B%3D1%40p%3D1695240090%40&hd=2023-09-23T08:00:59&hza=D&ar=false&s=true&d=false&hz=%5B%5D&fm=false&bp=false

...however, it does work on deltachat-ios, thunderbird, github ...

instead of the link, the hash `#sts` is clickable:

![Screenshot 2023-09-22 at 15 25 40](https://github.com/deltachat/message-parser/assets/9800740/3fccb652-f711-45af-b455-addce2709116)

reason is the umlaut - which is wrong somehow, but well, these are links in the wild still and are expected to work.

**Comment by farooqkz** [comment]
it might be possible that my PRs made this un-work :D

**Comment by Simon-Laux** [comment]
It's because of the `ü` in Glückstadt.
Which is a known issue https://github.com/deltachat/message-parser/issues/16, so this is a duplicated of that issue.
Anyways good to have another example that we can test against.

**Comment by farooqkz** [comment]
@Simon-Laux You should've closed this as invalid/duplicate/not-planned rather than "completed"
