### ISSUE TITLE
bug in email parsing: some bot commands are detected as email instead

### ISSUE THREAD

**Issue by adbenitez** [deltachat/message-parser#53]
commands like /command@bot@addr.com or  /something@example.com are detected as email addresses, they look clickable like commands and you try them thinking they will be set as draft, instead you land in a new chat with that weird address (this is another issue but for desktop, the chat should not be immediately created but user should get asked for confirmation)

input:
```
/command@bot@addr.com
```

expected:

```
[
    {
        "t": "BotCommandSuggestion",
        "c": "/command@bot@addr.com"
    }
]
```

actual:
```
[
    {
        "t": "EmailAddress",
        "c": "/command@bot"
    },
    {
        "t": "Text",
        "c": "@addr.com"
    }
]
```

**Comment by Simon-Laux** [comment]
could be related to #5 (I'm not sure if `/` can be part of an email address, but even if that were the case I think the fix would just be to give BotCommandSuggestions a higher priority than email addresses.
